### ISSUE TITLE
not compatible with Pike

### ISSUE THREAD

**Issue by byb121** [cancerit/cgp-dockstore#8]
### Actual behaviour

```
# probabaly need to unset proxy
$ unset http_proxy
$ unset https_proxy

$ scripts/pbuild.sh ubuntu yx2-test yx2-test ~/nfs_link/yx2-zeta-v3-cgp-prostate.sh 
Please enter your OpenStack Password for project cgp-prostate as user yx2: 
Could not find resource Ubuntu Xenial
```
Then I changed https://github.com/cancerit/cgp-dockstore/blob/562bcbc3d433ede9ec5d66188436729fd839961d/env/ubuntu/build.env#L3 to `export OS_BASE_IMAGE="Xenial"` and https://github.com/cancerit/cgp-dockstore/blob/562bcbc3d433ede9ec5d66188436729fd839961d/env/platform.env#L4 to export `OS_FIP_POOL="public"`

With OpenStack RC file - **identity API v3.0**
```
$ scripts/pbuild.sh ubuntu yx2-test yx2-test ~/nfs_link/yx2-zeta-v3-cgp-prostate.sh
Please enter your OpenStack Password for project cgp-prostate as user yx2: 
Template validation failed. Errors are shown below.

Errors validating build 'openstack'. 1 error(s) occurred:

* You must provide exactly one of DomainID or DomainName to authenticate by Username
```

 With OpenStack RC file - **identity API v2.0**
```
$ scripts/pbuild.sh ubuntu yx2-test yx2-test ~/nfs_link/yx2-zeta-cgp-prostate.sh
Please enter your OpenStack Password for project cgp-prostate as user yx2: 
Template validation failed. Errors are shown below.

Errors validating build 'openstack'. 1 error(s) occurred:

* No supported version available from endpoint https://zeta.internal.sanger.ac.uk:13000/
```

Have not got time of finding the solution yet.

### System information

* client OS + version - OS X - 10.11.6
* OpenStack Unified Client version - openstack 3.9.0
* Packer version - Packer v1.2.2

**Comment by keiranmraine** [comment]
Hmm, I'll be attempting to migrate across to Pike soon and will try to come up with a solution bw compatible solution.  I expected the v3.0 API item.

**Comment by keiranmraine** [comment]
Done, 2.1.0
